#!/usr/bin/env bash
#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
arch -arm64 brew install --formula <<< brew.formula
arch -arm64 brew install --formula <<< brew-arm64.formula
brew install --cask <<< brew.casks
brew tap homebrew/autoupdate
brew autoupdate start
brew tap instrumenta/instrumenta
mkdir -pv $HOME/.local/bin
{
  set -e
  wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-379.0.0-darwin-arm.tar.gz
  tar xf google-cloud-sdk-379.0.0-darwin-arm.tar.gz
  ./google-cloud-sdk/install.sh
  set +e
}
{
  set -e
  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/arm64/kubectl"
  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/arm64/kubectl.sha256"
  echo "$(cat kubectl.sha256)  kubectl" | shasum -a 256 --check
  install -m 0755 kubectl $HOME/.local/bin/kubectl
  install -m 0755 kubectl $HOME/.local/bin/k
  set +e
}
{
  set -e
  tmpdir="$(mktemp -d)"
  cd $tmpdir
  curl -LO https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-389.0.0-darwin-arm.tar.gz
  tar xf google-cloud-cli-389.0.0-darwin-arm.tar.gz
  cp -a ./google-cloud-sdk $HOME/.local/
  cd $HOME/.local/google-cloud-sdk
  ./install.sh
  set +e
}
{
  wget https://github.com/datreeio/datree/releases/download/1.6.10-rc/datree-cli_1.6.10-rc_Darwin_arm64.zip
  unzip datree-cli_1.6.10-rc_Darwin_arm64.zip
  install datree $HOME/.local/bin/
}
{
  wget https://github.com/kvz/json2hcl/releases/download/v0.1.1/json2hcl_0.1.1_darwin_arm64.tar.gz
  tar xf json2hcl_0.1.1_darwin_arm64.tar.gz
  install -m 0755 json2hcl $HOME/.local/bin/json2hcl
}
{
  wget https://github.com/einride/backstage-go/releases/download/v0.6.0/backstage-go_0.6.0_darwin_arm64.tar.gz
  tar xf backstage-go_0.6.0_darwin_arm64.tar.gz
  install -m 0755 backstage $HOME/.local/bin/backstage
}
exec ./setup-generic
