#!/usr/bin/env bash
set -euxo pipefail
python3 -m pip install --upgrade \
  powerline-status \
  stormssh
find . -mindepth 1 -maxdepth 1 -type d ! -name .git -printf "%f\0" | xargs -0 stow
if ! [[ -e ~/.vim/bundle/Vundle.vim ]]; then
	git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim
fi
if ! grep -q fish <<< "$SHELL"; then
	sudo chsh -s $(which fish) $USER
fi
curl -fksSLO https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
fish -c 'fundle install'

(
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  curl -fksSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
  tar zxvf krew.tar.gz &&
  KREW=./krew-"${OS}_${ARCH}" &&
  "$KREW" install krew
)
(
  ~/.local/bin/kubectl krew install ctx ns ingress-nginx minio neat konfig
  ~/.local/bin/kubectl krew update
  ~/.local/bin/kubectl krew upgrade
)
(
  curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh
  install -m 0755 kubectl-crossplane $HOME/.local/bin/kubectl-crossplane
  install -m 0755 kubectl-crossplane $HOME/.local/bin/crossplane
)
curl https://gcpdiag.dev/gcpdiag.sh -o $HOME/.local/bin/gcpdiag
chmod +x $HOME/.local/bin/gcpdiag
# TODO: gcloud components install gke-gcloud-auth-plugin
python3 -m pip install asciicast2movie
